USE softprog;

CREATE TABLE IF NOT EXISTS AREA (
	id INT AUTO_INCREMENT PRIMARY KEY NOT NULL, 
    nombre VARCHAR(50) NOT NULL, 
    activo BOOLEAN NOT NULL DEFAULT FALSE
);

CREATE TABLE IF NOT EXISTS CUENTA_USUARIO (
	id INT AUTO_INCREMENT PRIMARY KEY NOT NULL, 
    userName VARCHAR(50) NOT NULL,
    password VARCHAR(50) NOT NULL, 
    activo BOOLEAN NOT NULL DEFAULT FALSE
);

CREATE TABLE IF NOT EXISTS EMPLEADO (
	id INT AUTO_INCREMENT PRIMARY KEY NOT NULL, 
    idArea INT NOT NULL, 
    idCuentaUsuario INT NULL, 
    dni CHAR(8) NOT NULL, 
    nombre VARCHAR(50) NOT NULL, 
    apellidoPaterno VARCHAR(50) NOT NULL, 
    genero VARCHAR(10) NOT NULL, 
    fechaNacimiento DATE NOT NULL, 
    cargo VARCHAR(50) NOT NULL, 
    sueldo DECIMAL(10, 2) NOT NULL, 
    activo BOOLEAN NOT NULL DEFAULT FALSE
);

ALTER TABLE EMPLEADO
ADD CONSTRAINT FK_EMPLEADO_AREA 
FOREIGN KEY (idArea) REFERENCES AREA(id);

ALTER TABLE EMPLEADO
ADD CONSTRAINT FK_EMPLEADO_CUENTA_USUARIO
FOREIGN KEY (idCuentaUsuario) REFERENCES CUENTA_USUARIO(id);

CREATE TABLE CLIENTE (
	id INT AUTO_INCREMENT PRIMARY KEY NOT NULL, 
    idCuentaUsuario INT NULL, 
    dni CHAR(8) NOT NULL, 
    nombre VARCHAR(50) NOT NULL, 
    apellidoPaterno VARCHAR(50) NOT NULL, 
    genero VARCHAR(10) NOT NULL, 
    fechaNacimiento DATE NOT NULL, 
    categoria VARCHAR(50) NOT NULL, 
    lineaCredito DECIMAL(10, 2) NULL, 
    activo BOOLEAN NOT NULL DEFAULT FALSE
);

ALTER TABLE CLIENTE
ADD CONSTRAINT FK_CLIENTE_CUENTA_USUARIO
FOREIGN KEY (idCuentaUsuario) REFERENCES CUENTA_USUARIO(id);

CREATE TABLE PRODUCTO (
	id INT AUTO_INCREMENT PRIMARY KEY NOT NULL, 
    nombre VARCHAR(100) NOT NULL, 
    unidadMedida VARCHAR(10) NOT NULL, 
    precio DECIMAL(10, 2) NOT NULL, 
    activo BOOLEAN NOT NULL DEFAULT FALSE
);

CREATE TABLE ORDENVENTA (
	id INT AUTO_INCREMENT PRIMARY KEY NOT NULL, 
    idCliente INT NOT NULL, 
    idEmpleado INT NULL, 
    total DECIMAL(10, 2) NOT NULL, 
    activo BOOLEAN NOT NULL DEFAULT TRUE
);

ALTER TABLE ORDENVENTA
ADD CONSTRAINT FK_CLIENTE_ORDENVENTA
FOREIGN KEY (idCliente) REFERENCES CLIENTE(id);

ALTER TABLE ORDENVENTA
ADD CONSTRAINT FK_EMPLEADO_ORDENVENTA
FOREIGN KEY (idEmpleado) REFERENCES EMPLEADO(id);    

CREATE TABLE LINEAORDENVENTA (
	id INT AUTO_INCREMENT PRIMARY KEY NOT NULL, 
    idOrdenVenta INT NOT NULL, 
    idProducto INT NOT NULL, 
    cantidad INT NOT NULL, 
    subTotal DECIMAL(10, 2) NOT NULL, 
    activo BOOLEAN NOT NULL DEFAULT TRUE
);

ALTER TABLE LINEAORDENVENTA
ADD CONSTRAINT FK_LINEAORDENVENTA_ORDENVENTA
FOREIGN KEY (idOrdenVenta) REFERENCES ORDENVENTA(id);

ALTER TABLE LINEAORDENVENTA
ADD CONSTRAINT FK_LINEA0RDENVENTA_PRODUCTO
FOREIGN KEY (idProducto) REFERENCES PRODUCTO(id);