namespace SoftProgWeb.ViewModels;

public enum Cargo {
    GERENTE,
    DIRECTOR,
    SUBDIRECTOR,
    ASISTENTE,
    TECNICO,
    VENDEDOR_SENIOR,
    EJECUTIVO_COMERCIAL,
    ANALISTA_RRHH,
    ENCARGADO_ALMACEN,
    CONTADOR
}
