SELECT * FROM AREA;
SELECT * FROM PRODUCTO;
SELECT * FROM EMPLEADO;
SELECT * FROM CLIENTE;
SELECT * FROM CUENTA_USUARIO;

DELETE FROM PRODUCTO;
DELETE FROM EMPLEADO;
DELETE FROM CLIENTE;
DELETE FROM CUENTA_USUARIO;
DELETE FROM AREA;

DBCC CHECKIDENT ('AREA', RESEED, 0);
DBCC CHECKIDENT ('EMPLEADO', RESEED, 0);
DBCC CHECKIDENT ('CLIENTE', RESEED, 0);
DBCC CHECKIDENT ('CUENTA_USUARIO', RESEED, 0);
DBCC CHECKIDENT ('PRODUCTO', RESEED, 0);

