SET SQL_SAFE_UPDATES = 0;

DELETE FROM LINEAORDENVENTA;
DELETE FROM ORDENVENTA;
DELETE FROM EMPLEADO;
DELETE FROM CLIENTE;
DELETE FROM PRODUCTO;
DELETE FROM CUENTA_USUARIO;
DELETE FROM AREA;

ALTER TABLE AREA AUTO_INCREMENT = 1;
ALTER TABLE EMPLEADO AUTO_INCREMENT = 1;
ALTER TABLE CLIENTE AUTO_INCREMENT = 1;
ALTER TABLE CUENTA_USUARIO AUTO_INCREMENT = 1;
ALTER TABLE PRODUCTO AUTO_INCREMENT = 1;
ALTER TABLE LINEAORDENVENTA auto_increment = 1;
ALTER TABLE ORDENVENTA auto_increment = 1;