CREATE DATABASE Laboratorio;
GO

USE Laboratorio;
GO

IF OBJECT_ID('dbo.REG_PERSONAS', 'U') IS NOT NULL
    DROP TABLE dbo.REG_PERSONAS;

CREATE TABLE REG_PERSONAS (
  DNI CHAR(8) NOT NULL,
  PATERNO VARCHAR(45) NOT NULL,
  MATERNO VARCHAR(45) NOT NULL,
  NOMBRES VARCHAR(45) NOT NULL,
  PRIMARY KEY (DNI)
);
